const PROPERTY_GROUP = {
  layout: [
    "display",
    "float",
    "width",
    "min-width",
    "max-width",
    "height",
    "min-height",
    "max-height",
  ],
  position: ["position", "top", "right", "bottom", "left", "z-index"],
  spacing: [
    "margin",
    "margin-top",
    "margin-right",
    "margin-bottom",
    "margin-left",
    "padding",
    "padding-top",
    "padding-right",
    "padding-bottom",
    "padding-left",
  ],
  typography: [
    "font-size",
    "font-family",
    "font-weight",
    "font-style",
    "line-height",
    "text-align",
    "letter-spacing",
    "text-decoration",
    "text-transform",
    "text-shadow",
  ],
  border: [
    "border",
    "border-width",
    "border-style",
    "border-color",
    "border-radius",
    "box-shadow",
  ],
  color: ["color"],
  "background-color": ["background-color"],
};

export default PROPERTY_GROUP;
